### ISSUE TITLE
Target _blank on external links

### ISSUE THREAD

**Issue by miharekar** [RubySlovenia/RubySlovenia.github.io#16]
Social links should also in new window.

Also keep in mind comment by @otobrglez: "has to be GA tracked!"

**Comment by mfilej** [comment]
So 1999 :trollface:

**Comment by otobrglez** [comment]
@miharekar this is a blast from past.

P.s.: Do you want to revive this meetup. I have someone who would like to help us do just that.

**Comment by miharekar** [comment]
Zapiram issue za nazaj 🤷‍♂️

Sure, please do. Sj si ze reku da bos 😅
