### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by mrfoto** [RubySlovenia/RubySlovenia.github.io#19]
We had it [before](https://github.com/SloveniaRUG/SloveniaRUG.github.io/blob/20b9a72196e0bd69d2885fe79ce3ae87fc9ba9a4/404.html), so let's do it again with the new design.

**Comment by mfilej** [comment]
https://github.com/RubySlovenia/RubySlovenia.github.io/pull/30

**Comment by mfilej** [comment]
Works now: http://www.rug.si/foofoo

**Comment by mrfoto** [comment]
:tada:
