### ISSUE TITLE
Header causing horizontal slider to appear

### ISSUE THREAD

**Issue by lenart** [RubySlovenia/RubySlovenia.github.io#34]
Because header has `width: 100%` and additional `padding-left: 2px` a horizontal slider appears.

The problem should be solved by simply removing this line `padding-left` here https://github.com/RubySlovenia/RubySlovenia.github.io/blob/master/assets/css/rug14.sass#L163

**Comment by mrfoto** [comment]
Can you post a screenshot? #cantreproduce

**Comment by lenart** [comment]
Hope this helps.

![rug](https://cloud.githubusercontent.com/assets/9228/10937998/331279e4-82f7-11e5-867a-69f9f2e96609.gif)

![screen shot 2015-11-04 at 13 19 19](https://cloud.githubusercontent.com/assets/9228/10937999/33340500-82f7-11e5-8aa8-eafc86338db7.png)

**Comment by mfilej** [comment]
Cannot reproduce, seems to have been fixed at some point.
