### ISSUE TITLE
Rename to RubySlovenia

### ISSUE THREAD

**Issue by mrfoto** [RubySlovenia/RubySlovenia.github.io#7]
We're RubySlovenia everywhere - [meetup](http://www.meetup.com/RubySlovenia/), [twitter](https://twitter.com/rubyslovenia), [facebook](https://www.facebook.com/groups/RubySlovenia/). Should we rename this organization on github?

>Unexpected bad things will happen if you don't read this!
- We will create redirects for your repositories (web and git access)
- You will need to update your local repositories to point to the new location
- Renaming may take a few minutes to complete.

/cc @SloveniaRUG/owners

**Comment by mfilej** [comment]
Why not!

**Comment by mrfoto** [comment]
This will break all git repos you cloned and also probably cause some down-time for our website, because we'll have to rename this repo as well, but I think it's worth it.

**Comment by mfilej** [comment]
Doesn't GitHub handle renaming gracefully nowadays?

**Comment by mrfoto** [comment]
In this case no, because we're using organization pages. Which means: repo name == website name if repo name == [organization name].github.io

You can now change a [remote](https://help.github.com/articles/changing-a-remote-s-url/) or just delete and reclone the repo.
